version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.2 
jobs:
  frontend:
    docker:
      - image: windmillcode/angular-tornado-capybara-log4j2:0.0.6
    parallelism: 1
    environment:
    steps:
      - setup_remote_docker:
          docker_layer_caching:    
      - checkout    
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - npm-deps-v4-{{ checksum "/root/project/AngularApp/package.json" }}
     
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - bundle-deps-v1-{{ checksum "/root/project/AngularApp/testing/e2e/Gemfile.lock" }}

      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - site-packages-deps-v4-{{ checksum "/root/project/AngularApp/backend/python/requirements.txt" }}            

      - run:  
          
          . /etc/profile.d/01-custom-docker-setup.sh;    
          echo $PATH;
          cd ~/project/AngularApp/testing/e2e ; 
          bundle install;
          cd ~/project/AngularApp/backend/python;
          pip install -r requirements.txt --upgrade --target ./site-packages/linux;
          cd ~/project/AngularApp ;
          npm install -s;   
      - save_cache:
          key: npm-deps-v4-{{ checksum "/root/project/AngularApp/package.json" }}
          paths:
            - /root/project/AngularApp/node_modules  
      - save_cache:
          key: bundle-deps-v1-{{ checksum "/root/project/AngularApp/testing/e2e/Gemfile.lock" }}
          paths:
            - /root/project/AngularApp/testing/e2e/vendor/bundle  
      - save_cache:
          key: site-packages-deps-v4-{{ checksum "/root/project/AngularApp/backend/python/requirements.txt" }}   
          paths:
            - /root/project/AngularApp/backend/python/site-packages       
      - run:
          . /etc/profile.d/01-custom-docker-setup.sh;   
          cd ~/project/AngularApp;
          npx ng run AngularApp:judima:firebaseprod;
          npx firebase deploy --project auxillary-305605 --token $FIREBASE_TOKEN;

workflows:
  version: 2.1
  e2e:     
    jobs: 
      - frontend:  
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - master      
      